backend:
  name: github
  repo: pnochisaki/ahm
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pages"
    editor:
      preview: false

    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Left", name: "left", widget: "markdown"}
          - {label: "Right", name: "right", widget: "markdown"}
      - file: "src/pages/services/index.md"
        label: "Services"
        name: "services"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              [{label: "Service", name: "service", widget: "markdown"}]
      - file: "src/pages/resources/index.md"
        label: "Resources"
        name: "resources"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Left", name: "left", widget: "markdown"} 
          - {label: "Right", name: "right", widget: "markdown"} 
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}   
      - file: "src/pages/auto-injury/index.md"
        label: "Auto Injury"
        name: "auto-injury"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Left", name: "left", widget: "markdown"} 
          - {label: "Right", name: "right", widget: "markdown"} 
      - file: "src/pages/testimonials/index.md"
        label: "Testimonials"
        name: "testimonials"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: Testimonials, name: testimonials, widget: list, fields: [ {label: Author, name: author, widget: string}, {label: Quote, name: quote, widget: markdown}]}
